generator:
  class: sfDoctrineGenerator
  param:
    model_class:           page
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          page
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=title, url, created_at, updated_at]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
