<?php

/**
 * BaseCategoryRelations
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $type
 * @property integer $whmcs_gid
 * @property integer $category_id
 * @property Category $Category
 * 
 * @method integer           getType()        Returns the current record's "type" value
 * @method integer           getWhmcsGid()    Returns the current record's "whmcs_gid" value
 * @method integer           getCategoryId()  Returns the current record's "category_id" value
 * @method Category          getCategory()    Returns the current record's "Category" value
 * @method CategoryRelations setType()        Sets the current record's "type" value
 * @method CategoryRelations setWhmcsGid()    Sets the current record's "whmcs_gid" value
 * @method CategoryRelations setCategoryId()  Sets the current record's "category_id" value
 * @method CategoryRelations setCategory()    Sets the current record's "Category" value
 * 
 * @package    shop
 * @subpackage model
 * @author     Dmitriy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryRelations extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_relations');
        $this->hasColumn('type', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('whmcs_gid', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));
    }
}