<?php

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property boolean $is_shown_on_frontend
 * @property boolean $is_popular
 * @property string $image
 * @property Doctrine_Collection $Criterias
 * 
 * @method string              getName()                 Returns the current record's "name" value
 * @method boolean             getIsShownOnFrontend()    Returns the current record's "is_shown_on_frontend" value
 * @method boolean             getIsPopular()            Returns the current record's "is_popular" value
 * @method string              getImage()                Returns the current record's "image" value
 * @method Doctrine_Collection getCriterias()            Returns the current record's "Criterias" collection
 * @method Category            setName()                 Sets the current record's "name" value
 * @method Category            setIsShownOnFrontend()    Sets the current record's "is_shown_on_frontend" value
 * @method Category            setIsPopular()            Sets the current record's "is_popular" value
 * @method Category            setImage()                Sets the current record's "image" value
 * @method Category            setCriterias()            Sets the current record's "Criterias" collection
 * 
 * @package    shop
 * @subpackage model
 * @author     Dmitriy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_shown_on_frontend', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('is_popular', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CategoryRelations as Criterias', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}