<?php

/**
 * BaseShopCart
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $client_id
 * @property Doctrine_Collection $CartProducts
 * 
 * @method integer             getClientId()     Returns the current record's "client_id" value
 * @method Doctrine_Collection getCartProducts() Returns the current record's "CartProducts" collection
 * @method ShopCart            setClientId()     Sets the current record's "client_id" value
 * @method ShopCart            setCartProducts() Sets the current record's "CartProducts" collection
 * 
 * @package    shop
 * @subpackage model
 * @author     Dmitriy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShopCart extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shop_cart');
        $this->hasColumn('client_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CartProduct as CartProducts', array(
             'local' => 'id',
             'foreign' => 'cart_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}