<?php

/**
 * BaseCartProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cart_id
 * @property integer $category_id
 * @property integer $whmcs_pid
 * @property string $type
 * @property string $period
 * @property string $params
 * @property ShopCategory $ShopCategory
 * @property ShopCart $ShopCart
 * 
 * @method integer      getCartId()       Returns the current record's "cart_id" value
 * @method integer      getCategoryId()   Returns the current record's "category_id" value
 * @method integer      getWhmcsPid()     Returns the current record's "whmcs_pid" value
 * @method string       getType()         Returns the current record's "type" value
 * @method string       getPeriod()       Returns the current record's "period" value
 * @method string       getParams()       Returns the current record's "params" value
 * @method ShopCategory getShopCategory() Returns the current record's "ShopCategory" value
 * @method ShopCart     getShopCart()     Returns the current record's "ShopCart" value
 * @method CartProduct  setCartId()       Sets the current record's "cart_id" value
 * @method CartProduct  setCategoryId()   Sets the current record's "category_id" value
 * @method CartProduct  setWhmcsPid()     Sets the current record's "whmcs_pid" value
 * @method CartProduct  setType()         Sets the current record's "type" value
 * @method CartProduct  setPeriod()       Sets the current record's "period" value
 * @method CartProduct  setParams()       Sets the current record's "params" value
 * @method CartProduct  setShopCategory() Sets the current record's "ShopCategory" value
 * @method CartProduct  setShopCart()     Sets the current record's "ShopCart" value
 * 
 * @package    shop
 * @subpackage model
 * @author     Dmitriy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCartProduct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cart_product');
        $this->hasColumn('cart_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('whmcs_pid', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('period', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('params', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ShopCategory', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasOne('ShopCart', array(
             'local' => 'id',
             'foreign' => 'cart_id'));
    }
}