<?php

/**
 * BaseCategoryRelations
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $whmcs_gid
 * @property integer $category_id
 * @property ShopCategory $ShopCategory
 * @property ShopGroup $ShopGroup
 * 
 * @method integer           getWhmcsGid()     Returns the current record's "whmcs_gid" value
 * @method integer           getCategoryId()   Returns the current record's "category_id" value
 * @method ShopCategory      getShopCategory() Returns the current record's "ShopCategory" value
 * @method ShopGroup         getShopGroup()    Returns the current record's "ShopGroup" value
 * @method CategoryRelations setWhmcsGid()     Sets the current record's "whmcs_gid" value
 * @method CategoryRelations setCategoryId()   Sets the current record's "category_id" value
 * @method CategoryRelations setShopCategory() Sets the current record's "ShopCategory" value
 * @method CategoryRelations setShopGroup()    Sets the current record's "ShopGroup" value
 * 
 * @package    shop
 * @subpackage model
 * @author     Dmitriy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryRelations extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_relations');
        $this->hasColumn('whmcs_gid', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ShopCategory', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasOne('ShopGroup', array(
             'local' => 'whmcs_gid',
             'foreign' => 'id'));
    }
}