<?php

/**
 * BaseShopCartProductRelations
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cart_id
 * @property integer $product_id
 * @property ShopCart $ShopCart
 * @property CartProduct $CartProduct
 * 
 * @method integer                  getCartId()      Returns the current record's "cart_id" value
 * @method integer                  getProductId()   Returns the current record's "product_id" value
 * @method ShopCart                 getShopCart()    Returns the current record's "ShopCart" value
 * @method CartProduct              getCartProduct() Returns the current record's "CartProduct" value
 * @method ShopCartProductRelations setCartId()      Sets the current record's "cart_id" value
 * @method ShopCartProductRelations setProductId()   Sets the current record's "product_id" value
 * @method ShopCartProductRelations setShopCart()    Sets the current record's "ShopCart" value
 * @method ShopCartProductRelations setCartProduct() Sets the current record's "CartProduct" value
 * 
 * @package    shop
 * @subpackage model
 * @author     Dmitriy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShopCartProductRelations extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shop_cart_product_relations');
        $this->hasColumn('cart_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ShopCart', array(
             'local' => 'cart_id',
             'foreign' => 'id'));

        $this->hasOne('CartProduct', array(
             'local' => 'product_id',
             'foreign' => 'id'));
    }
}