<?php

/**
 * BaseShopCart
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $CartProduct
 * 
 * @method Doctrine_Collection getCartProduct() Returns the current record's "CartProduct" collection
 * @method ShopCart            setCartProduct() Sets the current record's "CartProduct" collection
 * 
 * @package    shop
 * @subpackage model
 * @author     Dmitriy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShopCart extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shop_cart');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CartProduct', array(
             'local' => 'cart_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}