<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('WhmcsDomainTld', 'doctrine');

/**
 * BaseWhmcsDomainTld
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $extension
 * @property string $dnsmanagement
 * @property string $emailforwarding
 * @property string $idprotection
 * @property string $eppcode
 * @property string $autoreg
 * @property integer $order
 * @property Doctrine_Collection $Prices
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getExtension()       Returns the current record's "extension" value
 * @method string              getDnsmanagement()   Returns the current record's "dnsmanagement" value
 * @method string              getEmailforwarding() Returns the current record's "emailforwarding" value
 * @method string              getIdprotection()    Returns the current record's "idprotection" value
 * @method string              getEppcode()         Returns the current record's "eppcode" value
 * @method string              getAutoreg()         Returns the current record's "autoreg" value
 * @method integer             getOrder()           Returns the current record's "order" value
 * @method Doctrine_Collection getPrices()          Returns the current record's "Prices" collection
 * @method WhmcsDomainTld      setId()              Sets the current record's "id" value
 * @method WhmcsDomainTld      setExtension()       Sets the current record's "extension" value
 * @method WhmcsDomainTld      setDnsmanagement()   Sets the current record's "dnsmanagement" value
 * @method WhmcsDomainTld      setEmailforwarding() Sets the current record's "emailforwarding" value
 * @method WhmcsDomainTld      setIdprotection()    Sets the current record's "idprotection" value
 * @method WhmcsDomainTld      setEppcode()         Sets the current record's "eppcode" value
 * @method WhmcsDomainTld      setAutoreg()         Sets the current record's "autoreg" value
 * @method WhmcsDomainTld      setOrder()           Sets the current record's "order" value
 * @method WhmcsDomainTld      setPrices()          Sets the current record's "Prices" collection
 * 
 * @package    shop
 * @subpackage model
 * @author     Dmitriy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWhmcsDomainTld extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tbldomainpricing');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('extension', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('dnsmanagement', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('emailforwarding', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('idprotection', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('eppcode', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('autoreg', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('order', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('WhmcsPrice as Prices', array(
             'local' => 'id',
             'foreign' => 'relid'));
    }
}