shop_category:
  class: sfDoctrineRouteCollection
  options:
    model:                ShopCategory
    module:               ShopCategory
    prefix_path:          /ShopCategory
    column:               id
    with_wildcard_routes: true

backend_page:
  class: sfDoctrineRouteCollection
  options:
    model:                Page
    module:               BackendPage
    prefix_path:          /page
    column:               id
    with_wildcard_routes: true

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }


# default rules
homepage:
  url:   /
  param: { module: BackendPage, action: index }
