page:
  class: sfDoctrineRouteCollection
  options:
    model:                page
    module:               page
    prefix_path:          /page
    column:               id
    with_wildcard_routes: true

category:
  class: sfDoctrineRouteCollection
  options:
    model:                category
    module:               category
    prefix_path:          /category
    column:               id
    with_wildcard_routes: true

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }


# default rules
homepage:
  url:   /
  param: { module: page, action: index }
