generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Page
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          backend_page
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: 'Page list'
        display: [=title, url, created_at, updated_at]
      filter:  ~
      form:    ~
      edit:
        title: 'Edit Page'
      new:
        title: 'New Page'
