<?php

/**
 * WhmcsDomainTldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WhmcsDomainTldTable extends PluginWhmcsDomainTldTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WhmcsDomainTldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WhmcsDomainTld');
    }
}