<?php

/**
 * CartProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    shop
 * @subpackage model
 * @author     Dmitriy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CartProduct extends BaseCartProduct
{
  /**
   * ShopProduct item for current CartProduct
   *
   * @var null|ShopProduct
   */
  protected $shopProduct = null;

  /**
   * Get ShopProduct item based on current CartProduct one
   *
   * @return null|ShopProduct
   */
  public function getShopProduct()
  {
    if(!$this->shopProduct)
    {
      // Find ShopProduct in case no ShopProduct saved locally
      $this->shopProduct = ShopProduct::findOneByTypeAndId($this->getType(), $this->getWhmcsPid());
    }
    return $this->shopProduct;
  }

  /**
   * Get Total CartProduct prices (from ShopProduct item)
   *
   * @param $currencyId
   * @return float Price
   */
  public function getTotalPrice($currencyId)
  {
    if($this->getShopProduct())
    {
      // Get Price object from ShopProduct item for provided currency and current billing period
      $price = $this->getShopProduct()->getPrice($currencyId, $this->getPeriod());
      if($price)
      {
        // If Price object is found - get it's total value
        return $price->getTotal();
      }
    }
    return null;
  }
}
