<?php

/**
 * ShopCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopCategoryTable extends Doctrine_Table
{
    const TABLE_NAME = 'ShopCategory';

    /**
     * Returns an instance of this class.
     *
     * @return object CategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable(self::TABLE_NAME);
    }

    /**
     * Update all Categories and disable Special flag
     *
     * @return int Number of updated rows
     * @throws Doctrine_Query_Exception
     */
    public function removeSpecials()
    {
        $query = Doctrine_Query::create()
            ->update(self::TABLE_NAME . " c")
            ->set('c.special', '?', 0)
            ->where('c.special = ?', 1);
        return $query->execute();
    }

    /**
     *
     * @return Doctrine_Collection
     * @throws Doctrine_Query_Exception
     */
    public function findSpecial()
    {
        return $this->findOneBy('special', 1);
    }

    /**
     * A list of Categories that have Popular and Shown on Frontend flags enabled
     *
     * @param int $limit Limit the number of categories. Unlimited if null
     * @return Doctrine_Collection List of Categories
     * @throws Doctrine_Query_Exception
     */
    public function findAllFrontend($limit = null)
    {
        $query = $this->createQuery('c')
            ->andWhere('c.is_shown_on_frontend = ?', true)
            ->andWhere('c.is_popular = ?', true);
        if($limit)
        {
            $query->limit($limit);
        }
        // TODO: Save result to cache
        return $query->execute();
    }
}