<?php

/**
 * ShopCartProductRelationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopCartProductRelationsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopCartProductRelationsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopCartProductRelations');
    }
}