<?php

/**
 * ShopGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopGroup');
    }

    /**
     * Override createQuery method to include non-hidden groups only
     *
     * @param string $alias
     * @return Doctrine_Query
     */
    public function createQuery($alias = '')
    {
        $query = parent::createQuery($alias);
        return $query->andWhere('hidden != ?', 'on');
    }
}