<?php

/**
 * ShopCartTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopCartTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopCartTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopCart');
    }

    /**
     * Remove carts older that provided number of days
     *
     * @param $daysOld Number of days old
     * @return int Number of removed records
     * @throws Doctrine_Query_Exception
     */
    public function removeOldCarts($daysOld)
    {
        $result = $this->createQuery('c')
            ->andWhere('DATEDIFF(NOW(), updated_at) > ?', $daysOld)
            ->delete()
            ->execute();
        return $result;
    }
}