# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: FrontendShopCategory, action: index }

change_language:
  url:   /change_language
  param: { module: Language, action: changeLanguage }

category:
  url:   /:sf_culture/:slug
  class:   sfDoctrineRoute
  options: { model: ShopCategory, type: object }
  param: { module: FrontendShopCategory, action: show }

page:
  url:   /:sf_culture/:url
  class:   sfDoctrineRoute
  options: { model: Page, type: object }
  param: { module: Page, action: show }
  requirements:
    url: .+