# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: FrontendShopCategory, action: index }

change_language:
  url:   /change_language
  param: { module: Language, action: changeLanguage }

cart:
  url:   /cart
  param: { module: ShopCart, action: index }

add_to_cart:
  url:   /addToCart
  class: sfRequestRoute
  param: { module: ShopCart, action: addToCart }
  requirements:
    sf_method: [post]

delete_from_cart:
  url:   /deleteFromCart
  class: sfRequestRoute
  param: { module: ShopCart, action: deleteFromCart }
  requirements:
    sf_method: [post]

update_cart:
  url:   /checkout
  param: { module: ShopCart, action: updateCart }

billing:
  url:   /billing
  param: { module: ShopCart, action: billing }

category:
  url:   /:sf_culture/category/:name
  class:   sfDoctrineRoute
  options: { model: ShopCategory, type: object, method: findOneByNameAndCulture }
  param: { module: FrontendShopCategory, action: show }

page:
  url:   /:sf_culture/:url
  class:   sfDoctrineRoute
  options: { model: Page, type: object }
  param: { module: Page, action: show }
  requirements:
    url: .+