<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('page_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'url' => 
             array(
              'type' => 'varchar',
              'unique' => '1',
              'length' => '255',
             ),
             'content' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->removeColumn('page', 'title');
        $this->removeColumn('page', 'url');
        $this->removeColumn('page', 'content');
    }

    public function down()
    {
        $this->dropTable('page_translation');
        $this->addColumn('page', 'title', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->addColumn('page', 'url', 'varchar', '255', array(
             'unique' => '1',
             ));
        $this->addColumn('page', 'content', 'string', '', array(
             ));
    }
}