<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('page_translation', 'page_translation_id_page_id', array(
             'name' => 'page_translation_id_page_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'page',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('page_translation', 'page_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('page_translation', 'page_translation_id_page_id');
        $this->removeIndex('page_translation', 'page_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}