<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version10 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('category_relations', 'category_relations_category_id_category_id');
        $this->createForeignKey('category_relations', 'category_relations_category_id_shop_category_id', array(
             'name' => 'category_relations_category_id_shop_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'shop_category',
             ));
        $this->createForeignKey('shop_category_translation', 'shop_category_translation_id_shop_category_id', array(
             'name' => 'shop_category_translation_id_shop_category_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'shop_category',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('category_relations', 'category_relations_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->addIndex('shop_category_translation', 'shop_category_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('category_relations', 'category_relations_category_id_category_id', array(
             'name' => 'category_relations_category_id_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'category',
             ));
        $this->dropForeignKey('category_relations', 'category_relations_category_id_shop_category_id');
        $this->dropForeignKey('shop_category_translation', 'shop_category_translation_id_shop_category_id');
        $this->removeIndex('category_relations', 'category_relations_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->removeIndex('shop_category_translation', 'shop_category_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}