<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version16 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('shop_cart', 'token', 'string', '', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('shop_cart', 'token');
    }
}