<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version17 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('cart_product', 'cart_product_category_id_shop_category_id', array(
             'name' => 'cart_product_category_id_shop_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'shop_category',
             ));
        $this->createForeignKey('cart_product', 'cart_product_cart_id_shop_cart_id', array(
             'name' => 'cart_product_cart_id_shop_cart_id',
             'local' => 'cart_id',
             'foreign' => 'id',
             'foreignTable' => 'shop_cart',
             ));
        $this->addIndex('cart_product', 'cart_product_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->addIndex('cart_product', 'cart_product_cart_id', array(
             'fields' => 
             array(
              0 => 'cart_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('cart_product', 'cart_product_category_id_shop_category_id');
        $this->dropForeignKey('cart_product', 'cart_product_cart_id_shop_cart_id');
        $this->removeIndex('cart_product', 'cart_product_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->removeIndex('cart_product', 'cart_product_cart_id', array(
             'fields' => 
             array(
              0 => 'cart_id',
             ),
             ));
    }
}