<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('shop_cart_product_relations', 'shop_cart_product_relations_cart_id_shop_cart_id', array(
             'name' => 'shop_cart_product_relations_cart_id_shop_cart_id',
             'local' => 'cart_id',
             'foreign' => 'id',
             'foreignTable' => 'shop_cart',
             ));
        $this->createForeignKey('shop_cart_product_relations', 'shop_cart_product_relations_product_id_cart_product_id', array(
             'name' => 'shop_cart_product_relations_product_id_cart_product_id',
             'local' => 'product_id',
             'foreign' => 'id',
             'foreignTable' => 'cart_product',
             ));
        $this->addIndex('shop_cart_product_relations', 'shop_cart_product_relations_cart_id', array(
             'fields' => 
             array(
              0 => 'cart_id',
             ),
             ));
        $this->addIndex('shop_cart_product_relations', 'shop_cart_product_relations_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('shop_cart_product_relations', 'shop_cart_product_relations_cart_id_shop_cart_id');
        $this->dropForeignKey('shop_cart_product_relations', 'shop_cart_product_relations_product_id_cart_product_id');
        $this->removeIndex('shop_cart_product_relations', 'shop_cart_product_relations_cart_id', array(
             'fields' => 
             array(
              0 => 'cart_id',
             ),
             ));
        $this->removeIndex('shop_cart_product_relations', 'shop_cart_product_relations_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
    }
}