<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version20 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('category_relations', 'category_relations_category_id_shop_category_id');
        $this->createForeignKey('category_relations', 'category_relations_category_id_shop_category_id_1', array(
             'name' => 'category_relations_category_id_shop_category_id_1',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'shop_category',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
    }

    public function down()
    {
        $this->createForeignKey('category_relations', 'category_relations_category_id_shop_category_id', array(
             'name' => 'category_relations_category_id_shop_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'shop_category',
             ));
        $this->dropForeignKey('category_relations', 'category_relations_category_id_shop_category_id_1');
    }
}