<?php

/**
 * PluginWhmcsPrice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginWhmcsPrice extends BaseWhmcsPrice
{
  public static function getDomainPriceTypes()
  {
    return [
      'domainregister',
      'domaintransfer',
      'domainrenew'
    ];
  }

  public static function getProductTypes()
  {
    return [
      'product'
    ];
  }

  public function getProductItem()
  {
    if(in_array($this->type, self::getDomainPriceTypes()))
    {
      return $this->getDomain();
    }

    if(in_array($this->type, self::getProductTypes()))
    {
      return $this->getProduct();
    }
  }

  public function getDomain()
  {
    return Doctrine::getTable('PluginWhmcsDomainTld')->findBy('id', $this->getRelid());
  }

  public function getProduct()
  {
    // TODO: Get product from API
  }
}