<?php

/**
 * PluginWhmcsPrice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginWhmcsPrice extends BaseWhmcsPrice
{
  /**
   * List of product types related to domains
   *
   * @return array
   */
  public static function getDomainPriceTypes()
  {
    return [
        self::getNewDomainPriceType(),
        'domaintransfer',
        'domainrenew'
    ];
  }

  /**
   * New domain product type
   *
   * @return string
   */
  public static function getNewDomainPriceType()
  {
    return 'domainregister';
  }

  /**
   * List of product types related to products
   *
   * @return array
   */
  public static function getProductTypes()
  {
    return [
      self::getNewProductType()
    ];
  }

  /**
   * New product type
   *
   * @return string
   */
  public static function getNewProductType()
  {
    return 'product';
  }
}