<?php

/**
 * PluginWhmcsDomainTldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWhmcsDomainTldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWhmcsDomainTldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWhmcsDomainTld');
    }
}