ShopCart:
  actAs:
    Timestampable: ~
  columns:
    client_id: { type: integer }

CartProduct:
  columns:
    cart_id: { type: integer, notnull: true }
    category_id: { type: integer, notnull: true }
    whmcs_pid: { type: integer, notnull: true }
    type: { type: string }
    period: { type: string }
    params: { type: string }
  relations:
    ShopCategory:
      local: category_id
      foreign: id
      foreignAlias: CartProducts
      type: one
      foreignType: many
    ShopCart:
      local: cart_id
      foreign: id
      foreignAlias: CartProducts
      type: one
      foreignType: many