ShopCart:
  actAs:
    Timestampable: ~

CartProduct:
  columns:
    cart_id: { type: integer, notnull: true }
    category_id: { type: integer, notnull: true }
    whmcs_pid: { type: integer, notnull: true }
    type: { type: string }
    period: { type: string }
    params: { type: string }
  relations:
    ShopCategory:
      local: id
      foreign: category_id
      type: one
      foreignType: many
    ShopCart:
      local: id
      foreign: cart_id
      type: one
      foreignType: many