ShopCategory:
  actAs:
    Timestampable: ~
    I18n:
      fields: [ name ]
  columns:
    name: { type: string(255), notnull: true }
    is_shown_on_frontend: { type: boolean, notnull: true, default: false }
    is_popular: { type: boolean, notnull: true, default: false }
    include_domains: { type: boolean, notnull: true, default: false }
    special: { type: boolean, notnull: true, default: false }
    image: { type: string(255) }
  relations:
    ShopGroups:
      class: ShopGroup
      foreignAlias: ShopCategories
      refClass: CategoryRelations
      local: category_id
      foreign: whmcs_gid

ShopGroup:
  tableName: tblproductgroups
  columns:
    id: { type: integer, notnull: true, autoincrement: true, primary: true }
    name: { type: string }
    orderfrmtpl: { type: string }
    disabledgateways: { type: string }
    hidden: { type: string }
    order: { type: int(1), default: 0}
  relations:
    WhmcsProductInternals:
      class: WhmcsProductInternal
      foreignAlias: ShopGroup
      local: id
      foreign: gid
      type: many
      foreignType: one

CategoryRelations:
  columns:
    whmcs_gid: { type: integer }
    category_id: { type: integer, notnull: true }
  relations:
    ShopCategory:
      local: category_id
      foreign: id
      foreignAlias: CategoryRelations
      onDelete: CASCADE
    ShopGroup:
      local: whmcs_gid
      foreign: id
      foreignAlias: CategoryRelations