Category:
  actAs:
    Timestampable: ~
    I18n:
      fields: [ name ]
  columns:
    name: { type: string(255), notnull: true }
    is_shown_on_frontend: { type: boolean, notnull: true, default: false }
    is_popular: { type: boolean, notnull: true, default: false }
    image: { type: string(255) }

CategoryRelations:
  columns:
    type: { type: integer(1), notnull: true }
    whmcs_gid: { type: integer }
    category_id: { type: integer }
  relations:
    Category:
      foreignAlias: Criterias
      local: category_id
      foreign: id
      type: one
      foreignType: many