Page:
  actAs: { Timestampable: ~ }
  columns:
    title: { type: string(255), notnull: true }
    url: { type: varchar(255), unique: true }
    meta_description: { type: varchar(255) }
    meta_keywords: { type: varchar(255) }
    content: { type: string }